import sys
import os
import glob
from pymatgen.core import Structure

# [!!! IMPORTANT !!!] Copy the manual XYZ generation function from earlier in our conversation
# because your pymatgen version doesn't support the built-in .to(fmt="xyz") method.
def generate_xyz_string(structure, comment_line="Generated by batch_extract_xyz.py"):
    """Manually generates the content for an XYZ file from a pymatgen structure."""
    xyz_lines = []
    xyz_lines.append(str(len(structure)))
    xyz_lines.append(comment_line)

    for site in structure:
        x, y, z = site.coords
        symbol = site.specie.symbol
        xyz_lines.append(f"{symbol}   {x:.6f}   {y:.6f}   {z:.6f}")
    
    return "\n".join(xyz_lines) + "\n"


def process_cif_files(source_dir, output_dir):
    # Expand user paths
    source_dir = os.path.expanduser(source_dir)
    output_dir = os.path.expanduser(output_dir)

    # Ensure output directory exists
    os.makedirs(output_dir, exist_ok=True)
    
    # Find all CIF files in the source directory
    cif_files = glob.glob(os.path.join(source_dir, '*.cif'))
    
    if not cif_files:
        print(f"No .cif files found in {source_dir}")
        return

    print(f"Found {len(cif_files)} CIF files. Starting extraction...")

    for cif_path in cif_files:
        try:
            # 1. Read the CIF file
            structure = Structure.from_file(cif_path)
            
            # 2. Generate XYZ string using the custom function
            comment = f"XYZ coordinates extracted from {os.path.basename(cif_path)}"
            xyz_string = generate_xyz_string(structure, comment)
            
            # 3. Define the output path (change extension to .xyz)
            base_filename = os.path.basename(cif_path)
            xyz_filename = os.path.splitext(base_filename)[0] + ".xyz"
            output_path = os.path.join(output_dir, xyz_filename)
            
            # 4. Save the XYZ file
            with open(output_path, "w") as f:
                f.write(xyz_string)
            
            print(f"  Success  Converted {base_filename} to {os.path.basename(output_path)}")

        except Exception as e:
            print(f"   Error processing file {cif_path}: {e}")

if __name__ == "__main__":
    # Define source and destination folders
    SOURCE_FOLDER = "~/Downloads/temp"
    OUTPUT_FOLDER = "~/param-scanner"
    
    process_cif_files(SOURCE_FOLDER, OUTPUT_FOLDER)
    print("\nBatch processing finished.")


